### ISSUE TITLE
Clarify case sensitivity on `list` command

### ISSUE THREAD

**Issue by Cheddam** [mighty-ops/sasquatch#32]
Currently if you have a playlist named `SweetTunesByRaltz` and you call `list sweettunesbyraltz`, Sasquatch will acknowledge your request but nothing will happen due to the variance in case. We should introduce more strict validation on this command to avoid confusion, or make it case-insensitive (and ensure new lists aren't case-variants of others).

**Comment by scott1702** [comment]
+1 case insensitive and negative response if it doesn't find the list

**Comment by scott1702** [comment]
Negative response fix https://github.com/mighty-ops/sasquatch/pull/36. But will work on case insensitivity later
