### ISSUE TITLE
Bug: Special characters are stripped out of the spotify username

### ISSUE THREAD

**Issue by ianherbert** [mighty-ops/sasquatch#37]
When copying the URI from Spotify and adding it via Slack eg: "list add anneslist spotify:user:silverstripe-engineroom:playlist:0HkcfuNesPrkF4BXxbCgTN" the dash is being stripped out of the username, so the list refers to silverstripeengineroom instead of silverstripe-engineroom.

**Comment by andrewandante** [comment]
Fixed in #38
